
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 05 22:58:12 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 35;
  public static final int CONST = 8;
  public static final int NUMCONST = 18;
  public static final int NOTEQUAL = 27;
  public static final int LPAREN = 40;
  public static final int SEMI = 37;
  public static final int GREATER = 28;
  public static final int CONTINUE = 16;
  public static final int INTERFACE = 5;
  public static final int LSQRBRAC = 44;
  public static final int LESS = 30;
  public static final int FOR = 14;
  public static final int MINUS = 22;
  public static final int RPAREN = 41;
  public static final int OROR = 33;
  public static final int LESSEQUAL = 31;
  public static final int COMMA = 38;
  public static final int CLASS = 4;
  public static final int DIV = 24;
  public static final int ANDAND = 32;
  public static final int PLUS = 21;
  public static final int IF = 9;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 36;
  public static final int RETURN = 17;
  public static final int EQUAL = 34;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int MOD = 25;
  public static final int IDENT = 46;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int EQUALDOUBLE = 26;
  public static final int RSQRBRAC = 45;
  public static final int GREATEREQUAL = 29;
  public static final int LBRACE = 42;
  public static final int ELSE = 7;
  public static final int ENUM = 6;
  public static final int READ = 12;
  public static final int CHARCONST = 19;
  public static final int RBRACE = 43;
  public static final int BOOLCONST = 20;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int PRINT = 11;
}

